//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



public partial class ListModelDataContext : Microsoft.SharePoint.Linq.DataContext
{

    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion

    public ListModelDataContext(string requestUrl) :
        base(requestUrl)
    {
        this.OnCreated();
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Condicao Pagamento")]
    public Microsoft.SharePoint.Linq.EntityList<Item> PaymentCondition
    {
        get
        {
            return this.GetList<Item>("Condicao Pagamento");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Grupo Cliente")]
    public Microsoft.SharePoint.Linq.EntityList<Item> ClientGroup
    {
        get
        {
            return this.GetList<Item>("Grupo Cliente");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Grupo Compras")]
    public Microsoft.SharePoint.Linq.EntityList<Item> PurchagesGroup
    {
        get
        {
            return this.GetList<Item>("Grupo Compras");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Grupo PBC")]
    public Microsoft.SharePoint.Linq.EntityList<Item> PbcGroup
    {
        get
        {
            return this.GetList<Item>("Grupo PBC");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Perfil Comercial")]
    public Microsoft.SharePoint.Linq.EntityList<Item> CommercialProfile
    {
        get
        {
            return this.GetList<Item>("Perfil Comercial");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Ramo Atividade")]
    public Microsoft.SharePoint.Linq.EntityList<Item> BranchActivity
    {
        get
        {
            return this.GetList<Item>("Ramo Atividade");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SBU")]
    public Microsoft.SharePoint.Linq.EntityList<Item> Sbu
    {
        get
        {
            return this.GetList<Item>("SBU");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Solicita Cliente")]
    public Microsoft.SharePoint.Linq.EntityList<ClientRequestItem> ClientRequest
    {
        get
        {
            return this.GetList<ClientRequestItem>("Solicita Cliente");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Sub-Ramo Atividade")]
    public Microsoft.SharePoint.Linq.EntityList<Item> SubBranchActivity
    {
        get
        {
            return this.GetList<Item>("Sub-Ramo Atividade");
        }
    }

    /// <summary>
    /// My List Instance
    /// </summary>
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Tarefa Cadastro Cliente")]
    public Microsoft.SharePoint.Linq.EntityList<TaskClientRegistrationItem> TaskClientRegistration
    {
        get
        {
            return this.GetList<TaskClientRegistrationItem>("Tarefa Cadastro Cliente");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Tipo Telefone")]
    public Microsoft.SharePoint.Linq.EntityList<Item> PhoneType
    {
        get
        {
            return this.GetList<Item>("Tipo Telefone");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Usuario Cadastro Cliente")]
    public Microsoft.SharePoint.Linq.EntityList<UserOfClientRegistrationItem> UserOfClientRegistration
    {
        get
        {
            return this.GetList<UserOfClientRegistrationItem>("Usuario Cadastro Cliente");
        }
    }
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "Item", Id = "0x01")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(ClientRequestItem))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(TaskClientRegistrationItem))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(UserOfClientRegistrationItem))]
public partial class Item : Microsoft.SharePoint.Linq.ITrackEntityState, Microsoft.SharePoint.Linq.ITrackOriginalValues, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging
{

    private System.Nullable<int> _id;

    private System.Nullable<int> _version;

    private string _path;

    private Microsoft.SharePoint.Linq.EntityState _entityState;

    private System.Collections.Generic.IDictionary<string, object> _originalValues;

    private string _title;

    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate();
    partial void OnCreated();
    #endregion

    Microsoft.SharePoint.Linq.EntityState Microsoft.SharePoint.Linq.ITrackEntityState.EntityState
    {
        get
        {
            return this._entityState;
        }
        set
        {
            if ((value != this._entityState))
            {
                this._entityState = value;
            }
        }
    }

    System.Collections.Generic.IDictionary<string, object> Microsoft.SharePoint.Linq.ITrackOriginalValues.OriginalValues
    {
        get
        {
            if ((null == this._originalValues))
            {
                this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
            }
            return this._originalValues;
        }
    }

    public Item()
    {
        this.OnCreated();
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "ID", Storage = "_id", ReadOnly = true, FieldType = "Counter")]
    public System.Nullable<int> Id
    {
        get
        {
            return this._id;
        }
        set
        {
            if ((value != this._id))
            {
                this.OnPropertyChanging("Id", this._id);
                this._id = value;
                this.OnPropertyChanged("Id");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "owshiddenversion", Storage = "_version", ReadOnly = true, FieldType = "Integer")]
    public System.Nullable<int> Version
    {
        get
        {
            return this._version;
        }
        set
        {
            if ((value != this._version))
            {
                this.OnPropertyChanging("Version", this._version);
                this._version = value;
                this.OnPropertyChanged("Version");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "FileDirRef", Storage = "_path", ReadOnly = true, FieldType = "Lookup", IsLookupValue = true)]
    public string Path
    {
        get
        {
            return this._path;
        }
        set
        {
            if ((value != this._path))
            {
                this.OnPropertyChanging("Path", this._path);
                this._path = value;
                this.OnPropertyChanged("Path");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Title", Storage = "_title", Required = true, FieldType = "Text")]
    public virtual string Title
    {
        get
        {
            return this._title;
        }
        set
        {
            if ((value != this._title))
            {
                this.OnPropertyChanging("Title", this._title);
                this._title = value;
                this.OnPropertyChanged("Title");
            }
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

    protected virtual void OnPropertyChanged(string propertyName)
    {
        if ((null != this.PropertyChanged))
        {
            this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }

    protected virtual void OnPropertyChanging(string propertyName, object value)
    {
        if ((null == this._originalValues))
        {
            this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
        }
        if ((false == this._originalValues.ContainsKey(propertyName)))
        {
            this._originalValues.Add(propertyName, value);
        }
        if ((null != this.PropertyChanging))
        {
            this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
        }
    }
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "ClientRequestContentType", Id = "0x01", List = "Solicita Cliente")]
public partial class ClientRequestItem : Item
{

    private string _seller;

    private string _registerId;

    private string _name;

    private string _contactFirstName;

    private string _contactLastName;

    private string _phoneFirstAreaCode;

    private string _contactFirstPhone;

    private string _contactFirstStation;

    private string _contactSecondName;

    private string _phoneSecondAreaCode;

    private string _contactSecondPhone;

    private string _contactSecondStation;

    private string _bank;

    private string _checkingAccountNumber;

    private string _checkingAccountCurrency;

    private string _agency;

    private string _emailBillet;

    private string _emailContact;

    private string _emailReport;

    private string _emailXml;

    private string _addressFullDelivery;

    private string _street;

    private string _streetNumber;

    private string _streetComplement;

    private string _district;

    private string _city;

    private string _state;

    private string _country;

    private string _cEP;

    private string _municipalRegistration;

    private string _priceList;

    private string _postage;

    private string _minimumBillingValue;

    private System.Nullable<System.DateTime> _volumeEffectiveDate;

    private string _volumeProductMix;

    private string _volumePenultimateTrimester;

    private string _volumeLastTrimester;

    private string _commission;

    private string _volumePurchages;

    private string _geographicRegion;

    private System.Nullable<RequestStatus> _requestStatus;

    private System.Nullable<RequestStep> _requestStep;

    private Microsoft.SharePoint.Linq.EntityRef<Item> _sbuId;

    private Microsoft.SharePoint.Linq.EntityRef<Item> _phoneFirstTypeId;

    private Microsoft.SharePoint.Linq.EntityRef<Item> _phoneSecondTypeId;

    private Microsoft.SharePoint.Linq.EntityRef<Item> _paymentConditionId;

    private Microsoft.SharePoint.Linq.EntityRef<Item> _pbcGroupId;

    private Microsoft.SharePoint.Linq.EntityRef<Item> _clientGroupId;

    private Microsoft.SharePoint.Linq.EntityRef<Item> _purchagesGroupId;

    private Microsoft.SharePoint.Linq.EntityRef<Item> _commercialProfileId;

    private Microsoft.SharePoint.Linq.EntityRef<Item> _branchActivityId;

    private Microsoft.SharePoint.Linq.EntityRef<Item> _subBranchActivityId;

    private System.Nullable<int> _requesterId;

    private string _requester;

    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate();
    partial void OnCreated();
    #endregion

    public ClientRequestItem()
    {
        this._sbuId = new Microsoft.SharePoint.Linq.EntityRef<Item>();
        this._sbuId.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnSbuIdSync);
        this._sbuId.OnChanged += new System.EventHandler(this.OnSbuIdChanged);
        this._sbuId.OnChanging += new System.EventHandler(this.OnSbuIdChanging);
        this._phoneFirstTypeId = new Microsoft.SharePoint.Linq.EntityRef<Item>();
        this._phoneFirstTypeId.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnPhoneFirstTypeIdSync);
        this._phoneFirstTypeId.OnChanged += new System.EventHandler(this.OnPhoneFirstTypeIdChanged);
        this._phoneFirstTypeId.OnChanging += new System.EventHandler(this.OnPhoneFirstTypeIdChanging);
        this._phoneSecondTypeId = new Microsoft.SharePoint.Linq.EntityRef<Item>();
        this._phoneSecondTypeId.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnPhoneSecondTypeIdSync);
        this._phoneSecondTypeId.OnChanged += new System.EventHandler(this.OnPhoneSecondTypeIdChanged);
        this._phoneSecondTypeId.OnChanging += new System.EventHandler(this.OnPhoneSecondTypeIdChanging);
        this._paymentConditionId = new Microsoft.SharePoint.Linq.EntityRef<Item>();
        this._paymentConditionId.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnPaymentConditionIdSync);
        this._paymentConditionId.OnChanged += new System.EventHandler(this.OnPaymentConditionIdChanged);
        this._paymentConditionId.OnChanging += new System.EventHandler(this.OnPaymentConditionIdChanging);
        this._pbcGroupId = new Microsoft.SharePoint.Linq.EntityRef<Item>();
        this._pbcGroupId.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnPbcGroupIdSync);
        this._pbcGroupId.OnChanged += new System.EventHandler(this.OnPbcGroupIdChanged);
        this._pbcGroupId.OnChanging += new System.EventHandler(this.OnPbcGroupIdChanging);
        this._clientGroupId = new Microsoft.SharePoint.Linq.EntityRef<Item>();
        this._clientGroupId.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnClientGroupIdSync);
        this._clientGroupId.OnChanged += new System.EventHandler(this.OnClientGroupIdChanged);
        this._clientGroupId.OnChanging += new System.EventHandler(this.OnClientGroupIdChanging);
        this._purchagesGroupId = new Microsoft.SharePoint.Linq.EntityRef<Item>();
        this._purchagesGroupId.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnPurchagesGroupIdSync);
        this._purchagesGroupId.OnChanged += new System.EventHandler(this.OnPurchagesGroupIdChanged);
        this._purchagesGroupId.OnChanging += new System.EventHandler(this.OnPurchagesGroupIdChanging);
        this._commercialProfileId = new Microsoft.SharePoint.Linq.EntityRef<Item>();
        this._commercialProfileId.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnCommercialProfileIdSync);
        this._commercialProfileId.OnChanged += new System.EventHandler(this.OnCommercialProfileIdChanged);
        this._commercialProfileId.OnChanging += new System.EventHandler(this.OnCommercialProfileIdChanging);
        this._branchActivityId = new Microsoft.SharePoint.Linq.EntityRef<Item>();
        this._branchActivityId.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnBranchActivityIdSync);
        this._branchActivityId.OnChanged += new System.EventHandler(this.OnBranchActivityIdChanged);
        this._branchActivityId.OnChanging += new System.EventHandler(this.OnBranchActivityIdChanging);
        this._subBranchActivityId = new Microsoft.SharePoint.Linq.EntityRef<Item>();
        this._subBranchActivityId.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnSubBranchActivityIdSync);
        this._subBranchActivityId.OnChanged += new System.EventHandler(this.OnSubBranchActivityIdChanged);
        this._subBranchActivityId.OnChanging += new System.EventHandler(this.OnSubBranchActivityIdChanging);
        this.OnCreated();
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Vendedor_x002f_Representante", Storage = "_seller", Required = true, FieldType = "Text")]
    public string Seller
    {
        get
        {
            return this._seller;
        }
        set
        {
            if ((value != this._seller))
            {
                this.OnPropertyChanging("Seller", this._seller);
                this._seller = value;
                this.OnPropertyChanged("Seller");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "CNPJ_x002f_CPFDatasul", Storage = "_registerId", Required = true, FieldType = "Text")]
    public string RegisterId
    {
        get
        {
            return this._registerId;
        }
        set
        {
            if ((value != this._registerId))
            {
                this.OnPropertyChanging("RegisterId", this._registerId);
                this._registerId = value;
                this.OnPropertyChanged("RegisterId");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "NomeFantasia", Storage = "_name", FieldType = "Text")]
    public string Name
    {
        get
        {
            return this._name;
        }
        set
        {
            if ((value != this._name))
            {
                this.OnPropertyChanging("Name", this._name);
                this._name = value;
                this.OnPropertyChanged("Name");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "ContatoPrimeiroNome", Storage = "_contactFirstName", Required = true, FieldType = "Text")]
    public string ContactFirstName
    {
        get
        {
            return this._contactFirstName;
        }
        set
        {
            if ((value != this._contactFirstName))
            {
                this.OnPropertyChanging("ContactFirstName", this._contactFirstName);
                this._contactFirstName = value;
                this.OnPropertyChanged("ContactFirstName");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "ContatoSobrenome", Storage = "_contactLastName", FieldType = "Text")]
    public string ContactLastName
    {
        get
        {
            return this._contactLastName;
        }
        set
        {
            if ((value != this._contactLastName))
            {
                this.OnPropertyChanging("ContactLastName", this._contactLastName);
                this._contactLastName = value;
                this.OnPropertyChanged("ContactLastName");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "C_x00f3_digoDDDContato", Storage = "_phoneFirstAreaCode", Required = true, FieldType = "Text")]
    public string PhoneFirstAreaCode
    {
        get
        {
            return this._phoneFirstAreaCode;
        }
        set
        {
            if ((value != this._phoneFirstAreaCode))
            {
                this.OnPropertyChanging("PhoneFirstAreaCode", this._phoneFirstAreaCode);
                this._phoneFirstAreaCode = value;
                this.OnPropertyChanged("PhoneFirstAreaCode");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "TelefonedoContato", Storage = "_contactFirstPhone", FieldType = "Text")]
    public string ContactFirstPhone
    {
        get
        {
            return this._contactFirstPhone;
        }
        set
        {
            if ((value != this._contactFirstPhone))
            {
                this.OnPropertyChanging("ContactFirstPhone", this._contactFirstPhone);
                this._contactFirstPhone = value;
                this.OnPropertyChanged("ContactFirstPhone");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "RamalContato", Storage = "_contactFirstStation", FieldType = "Text")]
    public string ContactFirstStation
    {
        get
        {
            return this._contactFirstStation;
        }
        set
        {
            if ((value != this._contactFirstStation))
            {
                this.OnPropertyChanging("ContactFirstStation", this._contactFirstStation);
                this._contactFirstStation = value;
                this.OnPropertyChanged("ContactFirstStation");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Contato2", Storage = "_contactSecondName", FieldType = "Text")]
    public string ContactSecondName
    {
        get
        {
            return this._contactSecondName;
        }
        set
        {
            if ((value != this._contactSecondName))
            {
                this.OnPropertyChanging("ContactSecondName", this._contactSecondName);
                this._contactSecondName = value;
                this.OnPropertyChanged("ContactSecondName");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "C_x00f3_digoDDDContato2", Storage = "_phoneSecondAreaCode", FieldType = "Text")]
    public string PhoneSecondAreaCode
    {
        get
        {
            return this._phoneSecondAreaCode;
        }
        set
        {
            if ((value != this._phoneSecondAreaCode))
            {
                this.OnPropertyChanging("PhoneSecondAreaCode", this._phoneSecondAreaCode);
                this._phoneSecondAreaCode = value;
                this.OnPropertyChanged("PhoneSecondAreaCode");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "TelefonedoContato2", Storage = "_contactSecondPhone", FieldType = "Text")]
    public string ContactSecondPhone
    {
        get
        {
            return this._contactSecondPhone;
        }
        set
        {
            if ((value != this._contactSecondPhone))
            {
                this.OnPropertyChanging("ContactSecondPhone", this._contactSecondPhone);
                this._contactSecondPhone = value;
                this.OnPropertyChanged("ContactSecondPhone");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "RamalContato2", Storage = "_contactSecondStation", FieldType = "Text")]
    public string ContactSecondStation
    {
        get
        {
            return this._contactSecondStation;
        }
        set
        {
            if ((value != this._contactSecondStation))
            {
                this.OnPropertyChanging("ContactSecondStation", this._contactSecondStation);
                this._contactSecondStation = value;
                this.OnPropertyChanged("ContactSecondStation");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Banco", Storage = "_bank", Required = true, FieldType = "Text")]
    public string Bank
    {
        get
        {
            return this._bank;
        }
        set
        {
            if ((value != this._bank))
            {
                this.OnPropertyChanging("Bank", this._bank);
                this._bank = value;
                this.OnPropertyChanged("Bank");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "N_x00fa_merodaCC", Storage = "_checkingAccountNumber", Required = true, FieldType = "Text")]
    public string CheckingAccountNumber
    {
        get
        {
            return this._checkingAccountNumber;
        }
        set
        {
            if ((value != this._checkingAccountNumber))
            {
                this.OnPropertyChanging("CheckingAccountNumber", this._checkingAccountNumber);
                this._checkingAccountNumber = value;
                this.OnPropertyChanged("CheckingAccountNumber");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "MoedadaCC", Storage = "_checkingAccountCurrency", FieldType = "Text")]
    public string CheckingAccountCurrency
    {
        get
        {
            return this._checkingAccountCurrency;
        }
        set
        {
            if ((value != this._checkingAccountCurrency))
            {
                this.OnPropertyChanging("CheckingAccountCurrency", this._checkingAccountCurrency);
                this._checkingAccountCurrency = value;
                this.OnPropertyChanged("CheckingAccountCurrency");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Ag_x00ea_ncia", Storage = "_agency", Required = true, FieldType = "Text")]
    public string Agency
    {
        get
        {
            return this._agency;
        }
        set
        {
            if ((value != this._agency))
            {
                this.OnPropertyChanging("Agency", this._agency);
                this._agency = value;
                this.OnPropertyChanged("Agency");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "E_x002d_mailBoleto", Storage = "_emailBillet", FieldType = "Text")]
    public string EmailBillet
    {
        get
        {
            return this._emailBillet;
        }
        set
        {
            if ((value != this._emailBillet))
            {
                this.OnPropertyChanging("EmailBillet", this._emailBillet);
                this._emailBillet = value;
                this.OnPropertyChanged("EmailBillet");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "E_x002d_mailContato", Storage = "_emailContact", Required = true, FieldType = "Text")]
    public string EmailContact
    {
        get
        {
            return this._emailContact;
        }
        set
        {
            if ((value != this._emailContact))
            {
                this.OnPropertyChanging("EmailContact", this._emailContact);
                this._emailContact = value;
                this.OnPropertyChanged("EmailContact");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "E_x002d_mailLaudo", Storage = "_emailReport", FieldType = "Text")]
    public string EmailReport
    {
        get
        {
            return this._emailReport;
        }
        set
        {
            if ((value != this._emailReport))
            {
                this.OnPropertyChanging("EmailReport", this._emailReport);
                this._emailReport = value;
                this.OnPropertyChanged("EmailReport");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "E_x002d_mailXML", Storage = "_emailXml", Required = true, FieldType = "Text")]
    public string EmailXml
    {
        get
        {
            return this._emailXml;
        }
        set
        {
            if ((value != this._emailXml))
            {
                this.OnPropertyChanging("EmailXml", this._emailXml);
                this._emailXml = value;
                this.OnPropertyChanged("EmailXml");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Endere_x00e7_odeEntregaCompleto", Storage = "_addressFullDelivery", FieldType = "Note")]
    public string AddressFullDelivery
    {
        get
        {
            return this._addressFullDelivery;
        }
        set
        {
            if ((value != this._addressFullDelivery))
            {
                this.OnPropertyChanging("AddressFullDelivery", this._addressFullDelivery);
                this._addressFullDelivery = value;
                this.OnPropertyChanged("AddressFullDelivery");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Logradouro", Storage = "_street", FieldType = "Text")]
    public string Street
    {
        get
        {
            return this._street;
        }
        set
        {
            if ((value != this._street))
            {
                this.OnPropertyChanging("Street", this._street);
                this._street = value;
                this.OnPropertyChanged("Street");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "N_x00fa_mero", Storage = "_streetNumber", FieldType = "Text")]
    public string StreetNumber
    {
        get
        {
            return this._streetNumber;
        }
        set
        {
            if ((value != this._streetNumber))
            {
                this.OnPropertyChanging("StreetNumber", this._streetNumber);
                this._streetNumber = value;
                this.OnPropertyChanged("StreetNumber");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Complemento", Storage = "_streetComplement", FieldType = "Text")]
    public string StreetComplement
    {
        get
        {
            return this._streetComplement;
        }
        set
        {
            if ((value != this._streetComplement))
            {
                this.OnPropertyChanging("StreetComplement", this._streetComplement);
                this._streetComplement = value;
                this.OnPropertyChanged("StreetComplement");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Bairro", Storage = "_district", FieldType = "Text")]
    public string District
    {
        get
        {
            return this._district;
        }
        set
        {
            if ((value != this._district))
            {
                this.OnPropertyChanging("District", this._district);
                this._district = value;
                this.OnPropertyChanged("District");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Cidade", Storage = "_city", FieldType = "Text")]
    public string City
    {
        get
        {
            return this._city;
        }
        set
        {
            if ((value != this._city))
            {
                this.OnPropertyChanging("City", this._city);
                this._city = value;
                this.OnPropertyChanged("City");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Estado", Storage = "_state", FieldType = "Text")]
    public string State
    {
        get
        {
            return this._state;
        }
        set
        {
            if ((value != this._state))
            {
                this.OnPropertyChanging("State", this._state);
                this._state = value;
                this.OnPropertyChanged("State");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Pa_x00ed_s", Storage = "_country", FieldType = "Text")]
    public string Country
    {
        get
        {
            return this._country;
        }
        set
        {
            if ((value != this._country))
            {
                this.OnPropertyChanging("Country", this._country);
                this._country = value;
                this.OnPropertyChanged("Country");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "CEP", Storage = "_cEP", FieldType = "Text")]
    public string CEP
    {
        get
        {
            return this._cEP;
        }
        set
        {
            if ((value != this._cEP))
            {
                this.OnPropertyChanging("CEP", this._cEP);
                this._cEP = value;
                this.OnPropertyChanged("CEP");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Inscri_x00e7__x00e3_oMunicipal", Storage = "_municipalRegistration", FieldType = "Text")]
    public string MunicipalRegistration
    {
        get
        {
            return this._municipalRegistration;
        }
        set
        {
            if ((value != this._municipalRegistration))
            {
                this.OnPropertyChanging("MunicipalRegistration", this._municipalRegistration);
                this._municipalRegistration = value;
                this.OnPropertyChanged("MunicipalRegistration");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "ListadePre_x00e7_o", Storage = "_priceList", FieldType = "Note")]
    public string PriceList
    {
        get
        {
            return this._priceList;
        }
        set
        {
            if ((value != this._priceList))
            {
                this.OnPropertyChanging("PriceList", this._priceList);
                this._priceList = value;
                this.OnPropertyChanged("PriceList");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Perfil_x002f_Porte", Storage = "_postage", FieldType = "Note")]
    public string Postage
    {
        get
        {
            return this._postage;
        }
        set
        {
            if ((value != this._postage))
            {
                this.OnPropertyChanging("Postage", this._postage);
                this._postage = value;
                this.OnPropertyChanged("Postage");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Valorm_x00ed_nimodefaturamento", Storage = "_minimumBillingValue", FieldType = "Text")]
    public string MinimumBillingValue
    {
        get
        {
            return this._minimumBillingValue;
        }
        set
        {
            if ((value != this._minimumBillingValue))
            {
                this.OnPropertyChanging("MinimumBillingValue", this._minimumBillingValue);
                this._minimumBillingValue = value;
                this.OnPropertyChanged("MinimumBillingValue");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Volume_x002d_DataVigencia", Storage = "_volumeEffectiveDate", FieldType = "DateTime")]
    public System.Nullable<System.DateTime> VolumeEffectiveDate
    {
        get
        {
            return this._volumeEffectiveDate;
        }
        set
        {
            if ((value != this._volumeEffectiveDate))
            {
                this.OnPropertyChanging("VolumeEffectiveDate", this._volumeEffectiveDate);
                this._volumeEffectiveDate = value;
                this.OnPropertyChanged("VolumeEffectiveDate");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Volume_x002d_MixdeProdutos", Storage = "_volumeProductMix", FieldType = "Text")]
    public string VolumeProductMix
    {
        get
        {
            return this._volumeProductMix;
        }
        set
        {
            if ((value != this._volumeProductMix))
            {
                this.OnPropertyChanging("VolumeProductMix", this._volumeProductMix);
                this._volumeProductMix = value;
                this.OnPropertyChanged("VolumeProductMix");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Volume_x002d_PenulltimoTrimestre", Storage = "_volumePenultimateTrimester", FieldType = "Text")]
    public string VolumePenultimateTrimester
    {
        get
        {
            return this._volumePenultimateTrimester;
        }
        set
        {
            if ((value != this._volumePenultimateTrimester))
            {
                this.OnPropertyChanging("VolumePenultimateTrimester", this._volumePenultimateTrimester);
                this._volumePenultimateTrimester = value;
                this.OnPropertyChanged("VolumePenultimateTrimester");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Volume_x002d_UltimoTrimestre", Storage = "_volumeLastTrimester", FieldType = "Text")]
    public string VolumeLastTrimester
    {
        get
        {
            return this._volumeLastTrimester;
        }
        set
        {
            if ((value != this._volumeLastTrimester))
            {
                this.OnPropertyChanging("VolumeLastTrimester", this._volumeLastTrimester);
                this._volumeLastTrimester = value;
                this.OnPropertyChanged("VolumeLastTrimester");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Comiss_x00e3_o_x0025_", Storage = "_commission", FieldType = "Text")]
    public string Commission
    {
        get
        {
            return this._commission;
        }
        set
        {
            if ((value != this._commission))
            {
                this.OnPropertyChanging("Commission", this._commission);
                this._commission = value;
                this.OnPropertyChanged("Commission");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "VolumeCompras", Storage = "_volumePurchages", FieldType = "Text")]
    public string VolumePurchages
    {
        get
        {
            return this._volumePurchages;
        }
        set
        {
            if ((value != this._volumePurchages))
            {
                this.OnPropertyChanging("VolumePurchages", this._volumePurchages);
                this._volumePurchages = value;
                this.OnPropertyChanged("VolumePurchages");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "RegiaoGeogr_x00e1_fica", Storage = "_geographicRegion", FieldType = "Text")]
    public string GeographicRegion
    {
        get
        {
            return this._geographicRegion;
        }
        set
        {
            if ((value != this._geographicRegion))
            {
                this.OnPropertyChanging("GeographicRegion", this._geographicRegion);
                this._geographicRegion = value;
                this.OnPropertyChanged("GeographicRegion");
            }
        }
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    [Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
    public override string Title
    {
        get
        {
            throw new System.InvalidOperationException("Field Title was removed from content type ClientRequestContentType.");
        }
        set
        {
            throw new System.InvalidOperationException("Field Title was removed from content type ClientRequestContentType.");
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Status", Storage = "_requestStatus", FieldType = "Choice")]
    public System.Nullable<RequestStatus> RequestStatus
    {
        get
        {
            return this._requestStatus;
        }
        set
        {
            if ((value != this._requestStatus))
            {
                this.OnPropertyChanging("RequestStatus", this._requestStatus);
                this._requestStatus = value;
                this.OnPropertyChanged("RequestStatus");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Etapa", Storage = "_requestStep", FieldType = "Choice")]
    public System.Nullable<RequestStep> RequestStep
    {
        get
        {
            return this._requestStep;
        }
        set
        {
            if ((value != this._requestStep))
            {
                this.OnPropertyChanging("RequestStep", this._requestStep);
                this._requestStep = value;
                this.OnPropertyChanged("RequestStep");
            }
        }
    }

    [Microsoft.SharePoint.Linq.AssociationAttribute(Name = "SBU", Storage = "_sbuId", MultivalueType = Microsoft.SharePoint.Linq.AssociationType.Single, List = "SBU")]
    public Item SbuId
    {
        get
        {
            return this._sbuId.GetEntity();
        }
        set
        {
            this._sbuId.SetEntity(value);
        }
    }

    [Microsoft.SharePoint.Linq.AssociationAttribute(Name = "TipodoTelefone", Storage = "_phoneFirstTypeId", MultivalueType = Microsoft.SharePoint.Linq.AssociationType.Single, List = "Tipo Telefone")]
    public Item PhoneFirstTypeId
    {
        get
        {
            return this._phoneFirstTypeId.GetEntity();
        }
        set
        {
            this._phoneFirstTypeId.SetEntity(value);
        }
    }

    [Microsoft.SharePoint.Linq.AssociationAttribute(Name = "TipodoTelefone2", Storage = "_phoneSecondTypeId", MultivalueType = Microsoft.SharePoint.Linq.AssociationType.Single, List = "Tipo Telefone")]
    public Item PhoneSecondTypeId
    {
        get
        {
            return this._phoneSecondTypeId.GetEntity();
        }
        set
        {
            this._phoneSecondTypeId.SetEntity(value);
        }
    }

    [Microsoft.SharePoint.Linq.AssociationAttribute(Name = "Condi_x00e7__x00e3_odePagamento", Storage = "_paymentConditionId", MultivalueType = Microsoft.SharePoint.Linq.AssociationType.Single, List = "Condicao Pagamento")]
    public Item PaymentConditionId
    {
        get
        {
            return this._paymentConditionId.GetEntity();
        }
        set
        {
            this._paymentConditionId.SetEntity(value);
        }
    }

    [Microsoft.SharePoint.Linq.AssociationAttribute(Name = "GrupoPBC", Storage = "_pbcGroupId", MultivalueType = Microsoft.SharePoint.Linq.AssociationType.Single, List = "Grupo PBC")]
    public Item PbcGroupId
    {
        get
        {
            return this._pbcGroupId.GetEntity();
        }
        set
        {
            this._pbcGroupId.SetEntity(value);
        }
    }

    [Microsoft.SharePoint.Linq.AssociationAttribute(Name = "GrupodeCliente", Storage = "_clientGroupId", MultivalueType = Microsoft.SharePoint.Linq.AssociationType.Single, List = "Grupo Cliente")]
    public Item ClientGroupId
    {
        get
        {
            return this._clientGroupId.GetEntity();
        }
        set
        {
            this._clientGroupId.SetEntity(value);
        }
    }

    [Microsoft.SharePoint.Linq.AssociationAttribute(Name = "GrupodeCompras", Storage = "_purchagesGroupId", MultivalueType = Microsoft.SharePoint.Linq.AssociationType.Single, List = "Grupo Compras")]
    public Item PurchagesGroupId
    {
        get
        {
            return this._purchagesGroupId.GetEntity();
        }
        set
        {
            this._purchagesGroupId.SetEntity(value);
        }
    }

    [Microsoft.SharePoint.Linq.AssociationAttribute(Name = "PerfilComercial", Storage = "_commercialProfileId", MultivalueType = Microsoft.SharePoint.Linq.AssociationType.Single, List = "Perfil Comercial")]
    public Item CommercialProfileId
    {
        get
        {
            return this._commercialProfileId.GetEntity();
        }
        set
        {
            this._commercialProfileId.SetEntity(value);
        }
    }

    [Microsoft.SharePoint.Linq.AssociationAttribute(Name = "RamodeAtividade", Storage = "_branchActivityId", MultivalueType = Microsoft.SharePoint.Linq.AssociationType.Single, List = "Ramo Atividade")]
    public Item BranchActivityId
    {
        get
        {
            return this._branchActivityId.GetEntity();
        }
        set
        {
            this._branchActivityId.SetEntity(value);
        }
    }

    [Microsoft.SharePoint.Linq.AssociationAttribute(Name = "Sub_x002d_ramoatividade", Storage = "_subBranchActivityId", MultivalueType = Microsoft.SharePoint.Linq.AssociationType.Single, List = "Sub-Ramo Atividade")]
    public Item SubBranchActivityId
    {
        get
        {
            return this._subBranchActivityId.GetEntity();
        }
        set
        {
            this._subBranchActivityId.SetEntity(value);
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Solicitante", Storage = "_requesterId", FieldType = "User", IsLookupId = true)]
    public System.Nullable<int> RequesterId
    {
        get
        {
            return this._requesterId;
        }
        set
        {
            if ((value != this._requesterId))
            {
                this.OnPropertyChanging("RequesterId", this._requesterId);
                this._requesterId = value;
                this.OnPropertyChanged("RequesterId");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Solicitante", Storage = "_requester", ReadOnly = true, FieldType = "User", IsLookupValue = true)]
    public string Requester
    {
        get
        {
            return this._requester;
        }
        set
        {
            if ((value != this._requester))
            {
                this.OnPropertyChanging("Requester", this._requester);
                this._requester = value;
                this.OnPropertyChanged("Requester");
            }
        }
    }

    private void OnSbuIdChanging(object sender, System.EventArgs e)
    {
        this.OnPropertyChanging("SbuId", this._sbuId.Clone());
    }

    private void OnSbuIdChanged(object sender, System.EventArgs e)
    {
        this.OnPropertyChanged("SbuId");
    }

    private void OnSbuIdSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e)
    {
    }

    private void OnPhoneFirstTypeIdChanging(object sender, System.EventArgs e)
    {
        this.OnPropertyChanging("PhoneFirstTypeId", this._phoneFirstTypeId.Clone());
    }

    private void OnPhoneFirstTypeIdChanged(object sender, System.EventArgs e)
    {
        this.OnPropertyChanged("PhoneFirstTypeId");
    }

    private void OnPhoneFirstTypeIdSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e)
    {
    }

    private void OnPhoneSecondTypeIdChanging(object sender, System.EventArgs e)
    {
        this.OnPropertyChanging("PhoneSecondTypeId", this._phoneSecondTypeId.Clone());
    }

    private void OnPhoneSecondTypeIdChanged(object sender, System.EventArgs e)
    {
        this.OnPropertyChanged("PhoneSecondTypeId");
    }

    private void OnPhoneSecondTypeIdSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e)
    {
    }

    private void OnPaymentConditionIdChanging(object sender, System.EventArgs e)
    {
        this.OnPropertyChanging("PaymentConditionId", this._paymentConditionId.Clone());
    }

    private void OnPaymentConditionIdChanged(object sender, System.EventArgs e)
    {
        this.OnPropertyChanged("PaymentConditionId");
    }

    private void OnPaymentConditionIdSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e)
    {
    }

    private void OnPbcGroupIdChanging(object sender, System.EventArgs e)
    {
        this.OnPropertyChanging("PbcGroupId", this._pbcGroupId.Clone());
    }

    private void OnPbcGroupIdChanged(object sender, System.EventArgs e)
    {
        this.OnPropertyChanged("PbcGroupId");
    }

    private void OnPbcGroupIdSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e)
    {
    }

    private void OnClientGroupIdChanging(object sender, System.EventArgs e)
    {
        this.OnPropertyChanging("ClientGroupId", this._clientGroupId.Clone());
    }

    private void OnClientGroupIdChanged(object sender, System.EventArgs e)
    {
        this.OnPropertyChanged("ClientGroupId");
    }

    private void OnClientGroupIdSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e)
    {
    }

    private void OnPurchagesGroupIdChanging(object sender, System.EventArgs e)
    {
        this.OnPropertyChanging("PurchagesGroupId", this._purchagesGroupId.Clone());
    }

    private void OnPurchagesGroupIdChanged(object sender, System.EventArgs e)
    {
        this.OnPropertyChanged("PurchagesGroupId");
    }

    private void OnPurchagesGroupIdSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e)
    {
    }

    private void OnCommercialProfileIdChanging(object sender, System.EventArgs e)
    {
        this.OnPropertyChanging("CommercialProfileId", this._commercialProfileId.Clone());
    }

    private void OnCommercialProfileIdChanged(object sender, System.EventArgs e)
    {
        this.OnPropertyChanged("CommercialProfileId");
    }

    private void OnCommercialProfileIdSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e)
    {
    }

    private void OnBranchActivityIdChanging(object sender, System.EventArgs e)
    {
        this.OnPropertyChanging("BranchActivityId", this._branchActivityId.Clone());
    }

    private void OnBranchActivityIdChanged(object sender, System.EventArgs e)
    {
        this.OnPropertyChanged("BranchActivityId");
    }

    private void OnBranchActivityIdSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e)
    {
    }

    private void OnSubBranchActivityIdChanging(object sender, System.EventArgs e)
    {
        this.OnPropertyChanging("SubBranchActivityId", this._subBranchActivityId.Clone());
    }

    private void OnSubBranchActivityIdChanged(object sender, System.EventArgs e)
    {
        this.OnPropertyChanged("SubBranchActivityId");
    }

    private void OnSubBranchActivityIdSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e)
    {
    }
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "TaskClientRegistratinContentType", Id = "0x01", List = "Tarefa Cadastro Cliente")]
public partial class TaskClientRegistrationItem : Item
{

    private string _observation;

    private System.Nullable<TaskStatus> _taskStatus;

    private System.Nullable<TaskStep> _taskStep;

    private Microsoft.SharePoint.Linq.EntityRef<Item> _request;

    private System.Nullable<int> _taskUserId;

    private string _taskUser;

    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate();
    partial void OnCreated();
    #endregion

    public TaskClientRegistrationItem()
    {
        this._request = new Microsoft.SharePoint.Linq.EntityRef<Item>();
        this._request.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnRequestSync);
        this._request.OnChanged += new System.EventHandler(this.OnRequestChanged);
        this._request.OnChanging += new System.EventHandler(this.OnRequestChanging);
        this.OnCreated();
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Observa_x00e7__x00e3_o", Storage = "_observation", FieldType = "Note")]
    public string Observation
    {
        get
        {
            return this._observation;
        }
        set
        {
            if ((value != this._observation))
            {
                this.OnPropertyChanging("Observation", this._observation);
                this._observation = value;
                this.OnPropertyChanged("Observation");
            }
        }
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    [Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
    public override string Title
    {
        get
        {
            throw new System.InvalidOperationException("Field Title was removed from content type TaskClientRegistratinContentType.");
        }
        set
        {
            throw new System.InvalidOperationException("Field Title was removed from content type TaskClientRegistratinContentType.");
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Status", Storage = "_taskStatus", Required = true, FieldType = "Choice")]
    public System.Nullable<TaskStatus> TaskStatus
    {
        get
        {
            return this._taskStatus;
        }
        set
        {
            if ((value != this._taskStatus))
            {
                this.OnPropertyChanging("TaskStatus", this._taskStatus);
                this._taskStatus = value;
                this.OnPropertyChanged("TaskStatus");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Fase", Storage = "_taskStep", Required = true, FieldType = "Choice")]
    public System.Nullable<TaskStep> TaskStep
    {
        get
        {
            return this._taskStep;
        }
        set
        {
            if ((value != this._taskStep))
            {
                this.OnPropertyChanging("TaskStep", this._taskStep);
                this._taskStep = value;
                this.OnPropertyChanged("TaskStep");
            }
        }
    }

    [Microsoft.SharePoint.Linq.AssociationAttribute(Name = "Solicitacao", Storage = "_request", MultivalueType = Microsoft.SharePoint.Linq.AssociationType.Single, List = "Solicita Cliente")]
    public Item Request
    {
        get
        {
            return this._request.GetEntity();
        }
        set
        {
            this._request.SetEntity(value);
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Usu_x00e1_rioTarefa", Storage = "_taskUserId", FieldType = "User", IsLookupId = true)]
    public System.Nullable<int> TaskUserId
    {
        get
        {
            return this._taskUserId;
        }
        set
        {
            if ((value != this._taskUserId))
            {
                this.OnPropertyChanging("TaskUserId", this._taskUserId);
                this._taskUserId = value;
                this.OnPropertyChanged("TaskUserId");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Usu_x00e1_rioTarefa", Storage = "_taskUser", ReadOnly = true, FieldType = "User", IsLookupValue = true)]
    public string TaskUser
    {
        get
        {
            return this._taskUser;
        }
        set
        {
            if ((value != this._taskUser))
            {
                this.OnPropertyChanging("TaskUser", this._taskUser);
                this._taskUser = value;
                this.OnPropertyChanged("TaskUser");
            }
        }
    }

    private void OnRequestChanging(object sender, System.EventArgs e)
    {
        this.OnPropertyChanging("Request", this._request.Clone());
    }

    private void OnRequestChanged(object sender, System.EventArgs e)
    {
        this.OnPropertyChanged("Request");
    }

    private void OnRequestSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e)
    {
    }
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "UserOfClientRegistrationContentType", Id = "0x01", List = "Usuario Cadastro Cliente")]
public partial class UserOfClientRegistrationItem : Item
{

    private System.Nullable<RegistrationGroup> _registrationGroup;

    private System.Nullable<int> _userId;

    private string _user;

    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate();
    partial void OnCreated();
    #endregion

    public UserOfClientRegistrationItem()
    {
        this.OnCreated();
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    [Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
    public override string Title
    {
        get
        {
            throw new System.InvalidOperationException("Field Title was removed from content type UserOfClientRegistrationContentType.");
        }
        set
        {
            throw new System.InvalidOperationException("Field Title was removed from content type UserOfClientRegistrationContentType.");
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Grupo", Storage = "_registrationGroup", Required = true, FieldType = "Choice")]
    public System.Nullable<RegistrationGroup> RegistrationGroup
    {
        get
        {
            return this._registrationGroup;
        }
        set
        {
            if ((value != this._registrationGroup))
            {
                this.OnPropertyChanging("RegistrationGroup", this._registrationGroup);
                this._registrationGroup = value;
                this.OnPropertyChanged("RegistrationGroup");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Usuario", Storage = "_userId", Required = true, FieldType = "User", IsLookupId = true)]
    public System.Nullable<int> UserId
    {
        get
        {
            return this._userId;
        }
        set
        {
            if ((value != this._userId))
            {
                this.OnPropertyChanging("UserId", this._userId);
                this._userId = value;
                this.OnPropertyChanged("UserId");
            }
        }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Usuario", Storage = "_user", ReadOnly = true, FieldType = "User", IsLookupValue = true)]
    public string User
    {
        get
        {
            return this._user;
        }
        set
        {
            if ((value != this._user))
            {
                this.OnPropertyChanging("User", this._user);
                this._user = value;
                this.OnPropertyChanged("User");
            }
        }
    }
}

public enum RequestStatus : int
{

    None = 0,

    Invalid = 1,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Pendente")]
    Pendente = 2,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Iniciado")]
    Iniciado = 4,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Finalizado")]
    Finalizado = 8,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Retorno")]
    Retorno = 16,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Reprovado")]
    Reprovado = 32,
}

public enum RequestStep : int
{

    None = 0,

    Invalid = 1,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Customer")]
    Customer = 2,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Fiscal")]
    Fiscal = 4,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "CAS")]
    CAS = 8,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Logistica")]
    Logistica = 16,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Crédito")]
    Crédito = 32,
}

public enum TaskStatus : int
{

    None = 0,

    Invalid = 1,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Pendente")]
    Pendente = 2,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Iniciado")]
    Iniciado = 4,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Aprovado")]
    Aprovado = 8,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Reprovado")]
    Reprovado = 16,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Retorno")]
    Retorno = 32,
}

public enum TaskStep : int
{

    None = 0,

    Invalid = 1,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Customer")]
    Customer = 2,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Fiscal")]
    Fiscal = 4,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "CAS")]
    CAS = 8,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Logistica")]
    Logistica = 16,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Crédito")]
    Crédito = 32,
}

public enum RegistrationGroup : int
{

    None = 0,

    Invalid = 1,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Customer")]
    Customer = 2,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Fiscal")]
    Fiscal = 4,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "CAS")]
    CAS = 8,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Logistica")]
    Logistica = 16,

    [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Crédito")]
    Crédito = 32,
}
